#!/usr/bin/env bash
#5-4_bad_luck_8_is_your_chance
i=1
while [ $i -le 10 ]
do
    if [ $i -eq 4 ]
    then
	
       echo "bad luck"
       
    elif [ $i -eq 8 ]
    then
	
	    echo "good luck"

       else
	   echo "Best School"
       fi
	    
       ((i++))
	   
done
