#!/usr/bin/env bash
#6-superstitious_numbers
i=1
while [ $i -le 20 ]
do
    if [ $i -eq 4 ]
    then
	echo "bad luck from China "
    elif [ $i -eq 9 ]
    then
	echo "bad luck from Japan"
    elif [ $i -eq 17 ]
    then
	echo "bad luck from Italy"
    else
	echo $i
    fi
    ((i++))
done
