#!/usr/bin/env bash
# Using a for loop to iterate through the content of the current directory
for item in *
do
   
    if [[ $item == .* ]]
    then
        continue 
    fi


    name_part=$(echo "$item" | cut -d '-' -f 2-)

    echo "$name_part"
done
