#!/usr/bin/env bash

# Define the filename
filename="school"

# Check if the file exists
if [ -e "$filename" ]; then
    echo "school file exists"

    # Check if the file is empty
    if [ -s "$filename" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    # Check if the file is a regular file
    if [ -f "$filename" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
