#!/usr/bin/env bash
# Create the PID file
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"

# Define signal handlers
trap 'echo "Y U no love me?!"' SIGINT
trap "sudo rm -f /var/run/holbertonscript.pid; exit" SIGQUIT
trap "sudo rm -f /var/run/holbertonscript.pid; echo I hate the kill command; exit" SIGTERM

# Infinite loop
while :
do
    echo "To infinity and beyond"
    sleep 2
done
