#!/usr/bin/env bash                                
# display all running PID                          
                                                   
while :                                            
do                                                 
        echo "I am alive!" >> /tmp/my_process      
        sleep 2                                    
done                                               
                                                   
                                                   
                                                   
                                                      
                                                   
                                                   
                                                   
           
